stages:
  - deploy

deploy-develop-server:
  # Use the official docker image.
  image: ictu/sshpass
  stage: deploy
  script:
    - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP
      "source ~/.nvm/nvm.sh && nvm use 18 && cd /home/ubuntu/Work/VarSwapIO/varswap-frontend && git add . && git reset --hard && git pull && yarn && yarn build && pm2 start var-fe && sudo service nginx restart"
  only:
    - main
#   when: manual
