import type { Metadata } from "next";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/notifications/styles.css';
import "./globals.css";
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'react-toastify/dist/ReactToastify.css';

import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import LayoutTemplate from "@/layout/layout.template";
import { Notifications } from "@mantine/notifications";


export const metadata: Metadata = {
  title: "VarSwap",
  description: "Generated by VarSwap",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mantine-color-scheme="dark" className="dark" suppressHydrationWarning>
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body suppressHydrationWarning={true} >
        <MantineProvider defaultColorScheme="dark">
          <Notifications />
          <LayoutTemplate>
            {children}
          </LayoutTemplate>
        </MantineProvider>
      </body>
    </html>
  );
}
